---
- name: Deploy application to EKS
  hosts: localhost
  connection: local  # Use local connection instead of SSH
  tasks:
    - name: Authenticate with EKS
      shell: |
        echo "Authenticating to EKS..."
        aws eks update-kubeconfig --name "{{ eks_cluster_name }}" --region ap-south-1
      register: auth_result
      failed_when: auth_result.rc != 0
      changed_when: false
      ignore_errors: false

    - name: Verify EKS cluster connection
      shell: |
        kubectl cluster-info
      register: cluster_info
      failed_when: cluster_info.rc != 0
      changed_when: false

    - name: Apply Kubernetes manifests for deployment
      shell: |
        echo "Applying Kubernetes Manifests..."
        kubectl apply -f ../k8s/deployment.yaml
        kubectl apply -f ../k8s/service.yaml
      when: cluster_info.rc == 0
      register: deploy_result
      failed_when: deploy_result.rc != 0
      changed_when: true

    - name: Output kubectl apply result
      debug:
        msg: "kubectl apply output: {{ deploy_result.stdout }}"
      when: deploy_result is defined and deploy_result.rc == 0

    - name: Check for kubectl apply errors
      debug:
        msg: "kubectl apply encountered errors: {{ deploy_result.stderr }}"
      when: deploy_result is defined and deploy_result.rc != 0

    - name: Output deployment results
      debug:
        msg: "Deployment completed successfully."
      when: deploy_result is defined and deploy_result.rc == 0

    - name: Handle failed authentication or deployment
      debug:
        msg: "Failed to authenticate with the EKS cluster or apply manifests."
      when: cluster_info.rc != 0 or deploy_result.rc != 0
